// ...existing code...
            iter = mandelbrot_iter(c_re, c_im); // o calculate_julia_iterations
            color = calculate_color(iter, MAX_ITER, 0);
            put_pixel(data, x, y, color);
// ...existing code...
